/** Material icon presets (SVG paths in lib/materialIconPaths.ts). */
export const MATERIAL_ICON_OPTIONS = [
  {title: 'Glass', value: 'glass'},
  {title: 'Textile', value: 'textile'},
  {title: 'Synthetic', value: 'synthetic'},
  {title: 'Metal', value: 'metal'},
  {title: 'Archive', value: 'archive'},
  {title: 'A/V', value: 'av'},
  {title: 'Performance', value: 'performance'},
  {title: 'Objects', value: 'objects'},
  {title: 'Paper', value: 'paper'},
  {title: 'Wood', value: 'wood'},
  {title: 'Ceramic', value: 'ceramic'},
  {title: 'Stone', value: 'stone'},
  {title: 'Photography', value: 'photography'},
  {title: 'Print', value: 'print'},
  {title: 'Painting', value: 'painting'},
  {title: 'Sculpture', value: 'sculpture'},
  {title: 'Installation', value: 'installation'},
  {title: 'Light', value: 'light'},
  {title: 'Sound', value: 'sound'},
  {title: 'Video', value: 'video'},
  {title: 'Ink', value: 'ink'},
  {title: 'Clay', value: 'clay'},
  {title: 'Resin', value: 'resin'},
  {title: 'Botanical', value: 'botanical'},
  {title: 'Leather', value: 'leather'},
  {title: 'Wax', value: 'wax'},
  {title: 'Digital', value: 'digital'},
  {title: 'Mixed media', value: 'mixed-media'},
  {title: 'Found object', value: 'found-object'},
  {title: 'Thread', value: 'thread'},
  {title: 'Plaster', value: 'plaster'},
  {title: 'Steel', value: 'steel'},
  {title: 'Textile print', value: 'textile-print'},
] as const

export type MaterialIconKey = (typeof MATERIAL_ICON_OPTIONS)[number]['value']
